### PR TITLE
v0.9.28 Fixed MapWriter.writeMapAsXml() error in releaseAddon

### PR DESCRIPTION
**Pull request by HaaiHenkie**
Also enabled finding scripts in dirs voor Gradle plugin in checkAddon,
so when addon build mind map is in src/addon it will check for
scripts in src/scripts and subdirectories.

freeplane/freeplane#1793

### CODE REVIEW

**Comment by macmarrum** [comment]
:heart:

I think add-ons, in general, should support the widest Freeplane-version range possible. **devtools** claims to work from v1.7.4. It would be great to keep the addon compatible with this version, while fixing it for higher versions.

Please see https://github.com/macmarrum/freeplane-PackAndGoGo/commit/44cd50ad577ba0ac1f12dba7d9b5701d881bf521

It would also be great if the mind-map (xml) version was as low as possible, to avoid notifications while openning .addon.mm on older Freeplane versions. This can be achieved by packaging the add-on using Freeplane "from version" (v1.7.4).

**Comment by HaaiHenkie** [comment]
Thanks @macmarrum! Smart thinking. I will change it accordingly.

**Comment by HaaiHenkie** [comment]
I have tested devtools v0.9.28. 

* releaseAddOn.groovy is working with Freeplane versions between 1.7.4 and 1.11.8 and after 1.11.8 (tested with 1.7.5, 1.11.6 and 1.11.12)
* checkAddOn.groovy is adding new script nodes from directory scripts/ relative to the add-on definition file (as it was) and from src/scripts/<language>/ while the add-on definition file is in src/addon/ as necessary when using the gradle plugin. Tested with src/addon/groovy and src/addon/javascript.

@dpolivaev, could you please accept this pull request and release v0.9.28 to SourceForge?

**Comment by HaaiHenkie** [comment]
@dpolivaev could you please merge this PR and release devtools v0.9.28 on SourceForge? Or is there anybody else who could do that?

**Comment by dpolivaev** [comment]
@HaaiHenkie  Can you merge it yourself? If you do not have the access rights please let me know. 
I am asking you because I am not the right person to review the add-on code, we are all in the same boat here.

**Comment by HaaiHenkie** [comment]
> @HaaiHenkie Can you merge it yourself? If you do not have the access rights please let me know. I am asking you because I am not the right person to review the add-on code, we are all in the same boat here.

@dpolivaev No, I do not have write access. Has @vboerchers disappeared from the add-on front?

**Comment by dpolivaev** [comment]
I invited you

**Comment by HaaiHenkie** [comment]
Hi @dpolivaev, I created a [draft release](https://github.com/freeplane/addons/releases) to attach devtools-v0.9.28.addon.mm and version.properties, since I cannot attach it to a comment like this. Could you publish them on Sourceforge? Or is that also something I could do myself?

**Pull request merged**
