### PR TITLE
Fix #2386 Special characters in add-on translations wrongly displayed

### PR DESCRIPTION
**Pull request by HaaiHenkie**
Replaced `StringEscapeUtils.escapeJava` with the new
`org.freeplane.core.util.TextUtils.escapeUtf8` in `encodeTranslations`.
The latter method prevents duplication of backslashes.

Removed method `encodeTranslations` from `releaseAddOn` since
`org.freeplane.main.addons.AddOnProperties` takes care of escaping with
`escapeUtf8`

I added all scripts directories in the repository as a source to the
build path. I added .settings/org.eclipse.jdt.groovy.core.prefs to
.gitignore.

### CODE REVIEW

**Comment by HaaiHenkie** [comment]
I changed the location of the source file and made a second commit. I make a new pull request and close this one.

**Comment by HaaiHenkie** [comment]
Reopened: I did not know that a second commit would appear automatically in the pull request

**Comment by HaaiHenkie** [comment]
Hi Volker,

I would like to emphasize that it is crucial to also change AddOnProperties.java in Freeplane, see my Freeplane pull request. Instead current solution I could also move method escapeUtf8 to AddOnProperties.java and using it instead of StringEscapeUtils.escapeJava. Bottom line is that AddOnProperties.java should stop using StringEscapeUtils.escapeJava.

I was wrestling with commons-lang-2.6.jar, that still needs to be on the build path of addons/devtools in Eclipse. It is shipped with Freeplane, so no need to put it in the lib folder of devtools. Previously it was available from the lib directory in the freeplane project. In the latest freeplane repositories. gradle collects the necessary libraries. As a workaround I made a relative path to commons-lang-2.6.jar in the lib directory of Freeplane compiled from the source projects. Do you know a better, more generic, solution?

**Comment by vboerchers** [comment]
Hello Henk,
thank you very much for your pull requests! I generally agree with your approach but I'd like to propose to place the two new escape functions into the Freeplane code base. From there `AddOnProperties` and scripts can use it. I suggest adding it to `TextUtils` (which is an official part of the scripting API) and to remove its code from `devtools`.

The fact that `escapeUtf8()` is idempotent is especially nice and I'm wondering if it wouldn'd be better to remove its application from `releaseAddOn` and keep it in `AddOnProperties`. Would that be possible or are there ways around `AddOnProperties`? If it's needed in `releaseAddOn` consider keeping escaping in both places. 

Best regards
Volker

**Comment by HaaiHenkie** [comment]
Hi Volker,

I will make the changes according to your suggestions.

I think `escapeUtf8()` can then be removed from `releaseAddOn`. I will still be in `encodeTranslations` which then can be used for troubleshooting escaping non-ASCII characters.

Best regards,

Henk

**Pull request merged**
